import { useEffect, useState } from "react";
import { api } from "../api";

export default function CartPage({ onBack }) {
  const [cart, setCart] = useState({ items: [], total: 0 });
  const [message, setMessage] = useState("");
  useEffect(() => { api("/cart").then(setCart).catch((error) => setMessage(error.message)); }, []);
  const remove = async (slug) => { try { setCart(await api(`/cart/items/${slug}`, { method: "DELETE" })); } catch (error) { setMessage(error.message); } };
  return <main className="min-h-screen bg-[#fffaf4]"><header className="border-b border-stone-200 bg-white"><div className="mx-auto flex h-[72px] max-w-4xl items-center justify-between px-5"><button onClick={onBack} className="text-lg font-black">← PLOT</button><span className="text-sm font-bold">SHOPPING CART</span></div></header><div className="mx-auto max-w-4xl px-5 py-10"><h1 className="text-3xl font-black">ตะกร้าของฉัน</h1><p className="mt-2 text-stone-500">บันทึกหนังสือที่สนใจไว้ แล้วชำระเงินเมื่อพร้อม</p>{message && <p className="mt-5 rounded-xl bg-red-50 px-4 py-3 text-red-700">{message}</p>}{!cart.items.length ? <div className="mt-8 rounded-3xl bg-white p-10 text-center shadow-sm ring-1 ring-stone-200"><p className="text-lg font-bold">ตะกร้าของคุณว่างอยู่</p><button onClick={onBack} className="mt-5 rounded-full bg-orange px-5 py-3 font-bold text-white">เลือกหนังสือ</button></div> : <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_280px]"><section className="overflow-hidden rounded-3xl bg-white ring-1 ring-stone-200">{cart.items.map(({ book }) => <div key={book.slug} className="flex gap-4 border-b border-stone-100 p-5 last:border-0"><div className="h-20 w-14 shrink-0 overflow-hidden rounded-lg bg-orange-100">{book.coverUrl && <img src={book.coverUrl} alt="" className="h-full w-full object-cover" />}</div><div className="min-w-0 flex-1"><h2 className="truncate font-bold">{book.title}</h2><p className="mt-1 text-sm text-stone-500">{book.contentType}</p><p className="mt-2 font-bold text-orange-600">{book.isFree ? "ฟรี" : `฿${book.price?.amount ?? 0}`}</p></div><button onClick={() => remove(book.slug)} className="self-start text-sm font-bold text-red-600">ลบ</button></div>)}</section><aside className="h-fit rounded-3xl bg-ink p-6 text-white"><h2 className="text-lg font-black">สรุปคำสั่งซื้อ</h2><div className="mt-5 flex justify-between border-b border-white/15 pb-4"><span>{cart.items.length} รายการ</span><b>฿{cart.total.toLocaleString()}</b></div><p className="mt-4 text-sm text-stone-300">ยังไม่มีการตัดเงิน หนังสือจะอยู่ในตะกร้าจนกว่าคุณจะชำระเงิน</p></aside></div>}</div></main>;
}
